### ISSUE TITLE
License

### ISSUE THREAD

**Issue by keesvandieren** [objectProgrammer/BytecoderGradle#3]
Hi,

We are making a Bytecoder libgdx backend (link: https://github.com/squins/gdx-backend-bytecoder).

We would like to have a Gradle plugin, but we cannot use or depend on GPL licensed dependencies, as many companies prohibits the use of it. 

Please consider changing it to another license, such as Apache license.

**Comment by ogrammer** [comment]
I will think about it, do note that this project is old and it might require some small edits to work with latest Bytecoder. I have some free time so I might update it even though last time I used Bytecoder was 1 year ago and then reconsider the license.

**Comment by ogrammer** [comment]
Updated for latest Bytecoder. I'm currently deciding license and if I change, it will probably be Apache or ISC.

**Comment by ogrammer** [comment]
@keesvandieren I think I will choose the license GPL+Classpath Exception which allows usage of the library and even embedding it in an executable without having to use that license.

It is the license used in the JDK itself. Would that be okay with you? If not, it's not a problem and I can choose another one.

I feel like a license in this style would be best because it allows the users to choose any license, the original intent of choosing the GPL was to make everyone benefit from improvements to BytecoderGradle itself, I never wanted to limit the users :)

https://openjdk.java.net/legal/gplv2+ce.html
https://resources.whitesourcesoftware.com/blog-whitesource/top-9-gpl-with-the-classpath-exception-questions-answered

Apologies for taking so long to answer, just randomly found your issue while browsing my old projects.

(Waiting for your response to make the new release, after 1 week I'll go with GPL+CE.)

**Comment by ogrammer** [comment]
Fixed by https://github.com/objectProgrammer/BytecoderGradle/commit/796b73db23e9b0e911b810d56b48899a07102265.
